package CNI.Crud.Exceptions;


  public enum ErrorCodes {
    // Codes d'erreur pour Formations
    FORMATION_NOT_FOUND(1000),
    FORMATION_NOT_VALID(1001),
    FORMATION_ALREADY_EXISTS(1002),
    FORMATION_IN_USE(1003),
    FORMATION_SAVE_ERROR(1004),
    FORMATION_FETCH_ERROR(1005),
    FORMATION_ALREADY_IN_USE(1006),
    FORMATION_DELETE_ERROR(1007),

    // Codes d'erreur pour Sessions
    SESSION_NOT_FOUND(2000),
    SESSION_NOT_VALID(2001),
    SESSION_ALREADY_EXISTS(2002),
    SESSION_FULL(2003),
    SESSION_IN_PROGRESS(2004),
    SESSION_COMPLETED(2005),
    SESSION_SAVE_ERROR(2006),
    SESSION_FETCH_ERROR(2007),
    SESSION_DELETE_ERROR(2008),
    

    // Codes d'erreur pour Utilisateurs
    UTILISATEUR_NOT_FOUND(3000),
    UTILISATEUR_NOT_VALID(3001),
    UTILISATEUR_ALREADY_EXISTS(3002),
    UTILISATEUR_EMAIL_ALREADY_EXISTS(3003),
    UTILISATEUR_INVALID_CREDENTIALS(3004),
    UTILISATEUR_INVALID_ROLE(3005),

    // Codes d'erreur pour Inscriptions
    INSCRIPTION_NOT_FOUND(4000),
    INSCRIPTION_NOT_VALID(4001),
    INSCRIPTION_ALREADY_EXISTS(4002),
    INSCRIPTION_CLOSED(4003),
    INSCRIPTION_PAYMENT_REQUIRED(4004),

    // Codes d'erreur pour Paiements
    PAIEMENT_NOT_FOUND(5000),
    PAIEMENT_NOT_VALID(5001),
    PAIEMENT_ALREADY_PROCESSED(5002),
    PAIEMENT_FAILED(5003),
    PAIEMENT_AMOUNT_INVALID(5004),

    // Codes d'erreur pour Salles
    SALLE_NOT_FOUND(6000),
    SALLE_NOT_VALID(6001),
    SALLE_ALREADY_EXISTS(6002),
    SALLE_NOT_AVAILABLE(6003),
    SALLE_CAPACITY_EXCEEDED(6004),

    // Codes d'erreur pour Themes
    THEME_NOT_FOUND(7000),
    THEME_NOT_VALID(7001),
    THEME_ALREADY_EXISTS(7002),
    THEME_IN_USE(7003),
    THEME_SAVE_ERROR(7004),
    THEME_FETCH_ERROR(7005),
    THEME_ALREADY_IN_USE(7006),
    THEME_DELETE_ERROR(7007),


    // Codes d'erreur pour Certificats
    CERTIFICAT_NOT_FOUND(8000),
    CERTIFICAT_NOT_VALID(8001),
    CERTIFICAT_ALREADY_GENERATED(8002),
    CERTIFICAT_GENERATION_FAILED(8003),

    // Codes d'erreur pour Commentaires
    COMMENTAIRE_NOT_FOUND(9000),
    COMMENTAIRE_NOT_VALID(9001),
    COMMENTAIRE_ALREADY_EXISTS(9002),
    COMMENTAIRE_NOT_AUTHORIZED(9003),

    // Codes d'erreur pour Notifications
    NOTIFICATION_NOT_FOUND(10000),
    NOTIFICATION_NOT_VALID(10001),
    NOTIFICATION_SENDING_FAILED(10002),

    // Erreurs techniques générales
    UPLOAD_FILE_FAILED(11000),
    DOWNLOAD_FILE_FAILED(11001),
    DATABASE_CONNECTION_FAILED(11002),
    INVALID_OPERATION(11003),
    UNAUTHORIZED_ACCESS(11004),
    VALIDATION_FAILED(11005),
    UTILISATEUR_CHANGE_PASSWORD_OBJECT_NOT_VALID(11006);



    private int code;

    ErrorCodes(int code) {
        this.code = code;
    }

    public int getCode() {
        return code;
    }
}