# Nom de l'application Spring
spring.application.name=stage_pfe_cni

# URL de la source de données (base de données)
spring.datasource.url=jdbc:mysql://localhost:3306/stage_pfe_cni
spring.datasource.username=root
spring.datasource.password=
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# Nom de la classe du driver JDBC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Stratégie de création du schéma de base de données par Hibernate
spring.jpa.hibernate.ddl-auto=update

# Affichage des requêtes SQL dans la console
spring.jpa.show-sql=false

# Définir le dialecte Hibernate à utiliser
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Formatage des requêtes SQL pour les rendre plus lisibles
spring.jpa.properties.hibernate.format_sql=true

# Flicker API configuration
flickr.apiKey=6bbe9fd03571561235b3dbd1b34eca62
flickr.apiSecret=1af0ccb5e3bb4d32

cors.allowed-api= http://localhost:4200
spring.main.allow-circular-references=true
spring.servlet.multipart.enabled=true

# Threshold after which files are written to disk
spring.servlet.multipart.file-size-threshold=2KB

# Max file size
spring.servlet.multipart.max-file-size=200MB

# Max request size
spring.servlet.multipart.max-request-size=215MB
# Mail Server Configuration
# Configuration de l'email


# Configuration de Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
# SMTP configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nerminemeddeb@gmail.com
spring.mail.password=fqhz iopm kozi mtju


# TLS sécurisé

spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.transport.protocol=smtp

spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.debug=true